In [51]:
import numpy as np

#Cria uma matriz triangular superior

def create_upper_triangular_binary_matrix(size):
    matrix = np.random.randint(2,size=(size, size))
    upper_triangular_matrix = np.triu(matrix)
    return upper_triangular_matrix

#muta a matrix triangular superior
def mutate_upper_triangular_binary(matrix):
    size = matrix.shape[0]
    
    # Choose a random position in the upper triangular part
    i = np.random.randint(0, size)
    j = np.random.randint(i, size)
    
    # Flip the chosen element's value (0 -> 1 or 1 -> 0)
    matrix[i, j] = 1 - matrix[i, j]
    
    return matrix

# Define the size of the matrix
matrix_size = 3

# Create an upper triangular binary matrix
upper_triangular_matrix = create_upper_triangular_binary_matrix(matrix_size)

print("Original Matrix:")
print(upper_triangular_matrix)

# Perform mutation
mutated_matrix = mutate_upper_triangular_binary(upper_triangular_matrix)

print("Mutated Matrix:")
print(mutated_matrix)

matrizFinal = mutated_matrix + mutated_matrix.T
for i in range(len(matrizFinal)):
    matrizFinal[i,i] = 0
print(matrizFinal)

Original Matrix:
[[0 0 0]
 [0 1 0]
 [0 0 0]]
Mutated Matrix:
[[0 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
